AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Simple VPC Template which
  includes VPC, Internet Gateway

Parameters:
  VpcCidr:
    Type: String
    Default: 10.0.0.0/16
    AllowedPattern: ^([0-9]{1,3}\.){3}[0-9]{1,3}\/(1[6-9]|2[0-8])$
    ConstraintDescription: >
      Must be a valid Cidr between /16 to /28
  Environment:
    Type: String
    AllowedValues:
      - "prod"
      - "dev"
    Default: "dev"
    Description: >
      VPC can be created only in dev and prod Environment

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Network Configuration
        Parameters:
          - VpcCidr
      - Label:
          default: Environment Settings
        Parameters:
          - Environment

# add condition to check the environment
Conditions:
  IsProd:
    Fn::Equals:
      - Ref: Environment
      - "prod"

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock:
        Ref: VpcCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value:
            Fn::Sub: "${Environment}-vpc"
        - Key: Environment
          Value:
            Ref: Environment

  # Internet Gateway for Internet access
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value:
            Fn::Sub: "${Environment}-igw"

  # Attach Internet Gateway to the VPC
  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: VPC
      InternetGatewayId:
        Ref: InternetGateway

  # Create Public Subnets
  PublicSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: ""
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value:
            Fn::Sub: "${Environment}-PublicSubnetA"
        - Key: Environment
          Value:
            Ref: Environment
        - Key: Owner
          Value: Platform Team
  PublicSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      CidrBlock: 10.0.2.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone:
        Fn::Select:
          - 1
          - Fn::GetAZs: ""
      Tags:
        - Key: Name
          Value:
            Fn::Sub: "${Environment}-PublicSubnetB"
        - Key: Environment
          Value:
            Ref: Environment
        - Key: Owner
          Value: Platform Team

  # Create Public Route Table
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: VPC
      Tags:
        - Key: Name
          Value:
            Fn::Sub: "${Environment}-public-route-table"
        - Key: Environment
          Value:
            Ref: Environment
        - Key: Owner
          Value: Platform Team

  # Create Public Route
  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: InternetGatewayAttachment
    Properties:
      RouteTableId:
        Ref: PublicRouteTable
      GatewayId:
        Ref: InternetGateway
      DestinationCidrBlock: 0.0.0.0/0
  # Public Subnet Association
  PublicSubnetAAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: PublicSubnetA
      RouteTableId:
        Ref: PublicRouteTable
  PublicSubnetBAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: PublicSubnetB
      RouteTableId:
        Ref: PublicRouteTable

  # Create private subnet for compute
  # Private Subnet A
  PrivateSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: ""
      CidrBlock: 10.0.11.0/24
      MapPublicIpOnLaunch: false
      VpcId:
        Ref: VPC
      Tags:
        - Key: Name
          Value:
            Fn::Sub: "${Environment}-PrivateSubnetA"
        - Key: Environment
          Value:
            Ref: Environment
        - Key: Owner
          Value: Platform Team
  # Private Subnet B
  PrivateSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Fn::Select:
          - 1
          - Fn::GetAZs: ""
      VpcId:
        Ref: VPC
      CidrBlock: 10.0.12.0/24
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value:
            Fn::Sub: "${Environment}-PrivateSubnetB"
        - Key: Environment
          Value:
            Ref: Environment
        - Key: Owner
          Value: Platform Team

  # Elastic IP for NAT GW A
  NatEipA:
    Type: AWS::EC2::EIP
    DependsOn: InternetGatewayAttachment
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value:
            Fn::Sub: "${Environment}-NatEipA"

  # NAT Gateway for private subnets in AZ-A
  NatGatewayA:
    Type: AWS::EC2::NatGateway
    DependsOn: InternetGatewayAttachment
    Properties:
      SubnetId:
        Ref: PublicSubnetA
      AllocationId:
        Fn::GetAtt: NatEipA.AllocationId
      Tags:
        - Key: Name
          Value:
            Fn::Sub: "${Environment}-NatGatewayA"

  # Elastic IP for NAT GW B (For prod only)
  NatEipB:
    Type: AWS::EC2::EIP
    DependsOn: InternetGatewayAttachment
    Condition: IsProd
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value:
            Fn::Sub: "${Environment}-NatEipB"

  # NAT Gateway (For prod only)
  NatGatewayB:
    Type: AWS::EC2::NatGateway
    DependsOn: InternetGatewayAttachment
    Condition: IsProd
    Properties:
      SubnetId:
        Ref: PublicSubnetB
      AllocationId:
        Fn::GetAtt: NatEipB.AllocationId
      Tags:
        - Key: Name
          Value:
            Fn::Sub: "${Environment}-NatGatewayB"

  # Private Route table in AZ-A
  PrivateRouteTableA:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: Name
          Value:
            Fn::Sub: "${Environment}-PrivateRouteTableA"
        - Key: Environment
          Value:
            Ref: Environment
        - Key: Owner
          Value: Platform Team
      VpcId:
        Ref: VPC

  # Private Route Table in AZ-B
  PrivateRouteTableB:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: VPC
      Tags:
        - Key: Name
          Value:
            Fn::Sub: "${Environment}-PrivateRouteTableB"
        - Key: Environment
          Value:
            Ref: Environment
        - Key: Owner
          Value: Platform Team

  # Default Private Route default to NatGatewayA
  PrivateRouteA:
    Type: AWS::EC2::Route
    DependsOn: NatGatewayA
    Properties:
      NatGatewayId:
        Ref: NatGatewayA
      RouteTableId:
        Ref: PrivateRouteTableA
      DestinationCidrBlock: 0.0.0.0/0

  # Default Private Route to NatGatewayB (For prod only)
  # [Note] DependsOn NatGatewayB is not explicitly
  # mentioned to keep code clear and simple
  PrivateRouteB:
    Type: AWS::EC2::Route
    Properties:
      NatGatewayId:
        Fn::If:
          - IsProd
          - Ref: NatGatewayB
          - Ref: NatGatewayA
      RouteTableId:
        Ref: PrivateRouteTableB
      DestinationCidrBlock: 0.0.0.0/0

  # Private Subnet in AZ-A Association with Nat Gateway AZ-A
  PrivateSubnetAAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: PrivateRouteTableA
      SubnetId:
        Ref: PrivateSubnetA

  # Private Subnet in AZ-B Association with Nat Gateway AZ-B
  PrivateSubnetBAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: PrivateSubnetB
      RouteTableId:
        Ref: PrivateRouteTableB

Outputs:
  VpcId:
    Description: VPC ID
    Value:
      Ref: VPC
    Export:
      Name:
        Fn::Sub: "${Environment}-VpcId"
  VpcCidrInfo:
    Value:
      Fn::GetAtt: VPC.CidrBlock
    Description: CIDR Block of the VPC
  PublicSubnetAId:
    Description: Public Subnet ID
    Value:
      Ref: PublicSubnetA
    Export:
      Name:
        Fn::Sub: "${Environment}-PublicSubnetA"
  PublicSubnetBId:
    Description: Public SubnetB ID
    Value:
      Ref: PublicSubnetB
    Export:
      Name:
        Fn::Sub: "${Environment}-PublicSubnetB"
  PrivateSubnetAId:
    Description: Private Subnet A ID
    Value:
      Ref: PrivateSubnetA
    Export:
      Name:
        Fn::Sub: "${Environment}-PrivateSubnetA"
  PrivateSubnetBId:
    Description: Private Subnet B ID
    Value:
      Ref: PrivateSubnetB
    Export:
      Name:
        Fn::Sub: "${Environment}-PrivateSubnetB"
