AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Simple VPC Template which
  includes VPC, Internet Gateway

Parameters:
  VpcCidr:
    Type: String
    Default: 10.0.0.0/16
    AllowedPattern: ^([0-9]{1,3}\.){3}[0-9]{1,3}\/(1[6-9]|2[0-8])$
    ConstraintDescription: >
      Must be a valid Cidr between /16 to /28
  Environment:
    Type: String
    AllowedValues:
      - "prod"
      - "dev"
    Default: "dev"
    Description: >
      VPC can be created only in dev and prod Environment

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Network Configuration
        Parameters:
          - VpcCidr
      - Label:
          default: Environment Settings
        Parameters:
          - Environment

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-vpc"
        - Key: Environment
          Value: !Ref Environment

# Internet Gateway for Internet access
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-igw"

# Attach Internet Gateway to the VPC
  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

# Create Public Subnets
  PublicSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [0, !GetAZs ""]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: public-subnet
        - Key: Environment
          Value: !Sub ${Environment}
        - Key: Owner
          Value: Platform Team
  PublicSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.2.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [1, !GetAZs ""]
      Tags:
        - Key: Name
          Value: public-subnet
        - Key: Environment
          Value: !Sub ${Environment}
        - Key: Owner
          Value: Platform Team
  # Create Route Table
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-public-route-table"
        - Key: Environment
          Value: !Sub ${Environment}
        - Key: Owner
          Value: Platform Team
# Create Public Route
  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: InternetGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      GatewayId: !Ref InternetGateway
      DestinationCidrBlock: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-public-route"
        - Key: Environment
          Value: !Sub ${Environment}
        - Key: Owner
          Value: Platform Team
# Subnet Association
  PublicSubnetAAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetA
      RouteTableId: !Ref PublicRouteTable
  PublicSubnetBAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetB
      RouteTableId: !Ref PublicRouteTable

Outputs:
  VpcId:
    Description: VPC ID
    Value: !Ref VPC
    Export:
      Name: !Sub "${Environment}-VpcId"
  VpcCidrInfo:
    Value: !GetAtt VPC.CidrBlock
    Description: CIDR Block of the VPC
  PublicSubnetAId:
    Description: Public Subnet ID
    Value: !Ref PublicSubnetA
    Export:
      Name: !Sub "${Environment}-PublicSubnetA"
  PublicSubnetBId:
    Description: Public SubnetB ID
    Value: !Ref PublicSubnetB
    Export:
      Name: !Sub "${Environment}-PublicSubnetB"
